backend:
  name: git-gateway
  branch: main # تأكد أن هذا هو اسم الفرع الرئيسي لمشروعك على GitHub (غالباً main أو master)

media_folder: "public/images" # المجلد الذي سيتم حفظ الصور فيه
public_folder: "/images" # المسار العام للصور في موقعك

collections:
  - name: "global"
    label: "الإعدادات العامة"
    files:
      - file: "public/data/global.json"
        label: "إعدادات الموقع"
        name: "global_settings"
        fields:
          - {label: "عنوان الصفحة (عربي)", name: "page_title_ar", widget: "string"}
          - {label: "عنوان الصفحة (إنجليزي)", name: "page_title_en", widget: "string"}
          - {label: "اسم المصمم (عربي)", name: "designer_name_ar", widget: "string"}
          - {label: "اسم المصمم (إنجليزي)", name: "designer_name_en", widget: "string"}
          - {label: "الوصف التعريفي (عربي)", name: "hero_description_ar", widget: "text"}
          - {label: "الوصف التعريفي (إنجليزي)", name: "hero_description_en", widget: "text"}
          - {label: "العنوان الوصفي (عربي)", name: "tagline_ar", widget: "string"}
          - {label: "العنوان الوصفي (إنجليزي)", name: "tagline_en", widget: "string"}
          - {label: "وصف الموقع (عربي)", name: "meta_description_ar", widget: "string"}
          - {label: "وصف الموقع (إنجليزي)", name: "meta_description_en", widget: "string"}
          - {label: "صورة البروفايل", name: "profile_image", widget: "image", default: "/images/placeholder-profile.png"}
          - {label: "أيقونة الموقع (Favicon)", name: "favicon", widget: "image", default: "/images/placeholder-favicon.png"}
          - {label: "البريد الإلكتروني للتواصل", name: "contact_email", widget: "string", pattern: ["^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$", "يجب أن يكون بريد إلكتروني صحيح"], required: false}
          - {label: "رقم الهاتف للتواصل", name: "contact_phone", widget: "string", required: false}
          - {label: "روابط التواصل الاجتماعي", name: "social_links", widget: "list", allow_add: true, fields:
              - {label: "اسم المنصة", name: "platform_name", widget: "string"}
              - {label: "الرابط", name: "url", widget: "string"}
              - {label: "أيقونة (اسم Lucide Icon)", name: "icon", widget: "string", hint: "مثال: Facebook, Linkedin, Twitter"}

  - name: "legal"
    label: "المعلومات القانونية"
    files:
      - file: "public/data/legal.json"
        label: "معلومات قانونية"
        name: "legal_info"
        fields:
          - {label: "عنوان الصفحة (عربي)", name: "title_ar", widget: "string"}
          - {label: "عنوان الصفحة (إنجليزي)", name: "title_en", widget: "string"}
          - {label: "محتوى الصفحة (عربي)", name: "content_ar", widget: "markdown"}
          - {label: "محتوى الصفحة (إنجليزي)", name: "content_en", widget: "markdown"}

  - name: "specializations"
    label: "التخصصات"
    files:
      - file: "public/data/specializations.json"
        label: "قائمة التخصصات"
        name: "specializations_list"
        fields:
          - {label: "التخصصات", name: "specializations", widget: "list", allow_add: true, fields:
              - {label: "اسم التخصص (عربي)", name: "name_ar", widget: "string"}
              - {label: "اسم التخصص (إنجليزي)", name: "name_en", widget: "string"}
              - {label: "أيقونة (اسم Lucide Icon)", name: "icon", widget: "string", hint: "مثال: PenTool, Palette, Lightbulb"}
              - {label: "عنوان URL للتصنيف (Slug)", name: "category_slug", widget: "string"}

  - name: "portfolio"
    label: "معرض الأعمال"
    files:
      - file: "public/data/portfolio.json"
        label: "قائمة المشاريع"
        name: "portfolio_projects"
        fields:
          - {label: "المشاريع", name: "projects", widget: "list", allow_add: true, fields:
              - {label: "معرف المشروع (ID)", name: "id", widget: "string", hint: "يجب أن يكون فريداً لكل مشروع"}
              - {label: "عنوان المشروع (عربي)", name: "title_ar", widget: "string"}
              - {label: "عنوان المشروع (إنجليزي)", name: "title_en", widget: "string"}
              - {label: "وصف قصير (عربي)", name: "short_description_ar", widget: "text", required: false}
              - {label: "وصف قصير (إنجليزي)", name: "short_description_en", widget: "text", required: false}
              - {label: "الصورة الرئيسية", name: "main_image", widget: "image", default: "/images/placeholder-project.png"}
              - {label: "صور إضافية", name: "additional_images", widget: "list", required: false, fields:
                  - {label: "صورة", name: "image", widget: "image", default: "/images/placeholder-additional.png"}
              - {label: "التصنيف", name: "category", widget: "select", options: ["logos", "branding", "advertising", "ui-design"], default: "logos", hint: "يجب أن يتطابق مع 'عنوان URL للتصنيف (Slug)' في التخصصات"}
              - {label: "رابط المشروع (اختياري)", name: "project_url", widget: "string", required: false}
              - {label: "محتوى المشروع (عربي)", name: "body_ar", widget: "markdown", required: false}
              - {label: "محتوى المشروع (إنجليزي)", name: "body_en", widget: "markdown", required: false}

